require("colorschemes.kanagawa")
require("colorschemes.catppuccin")
require("colorschemes.tokyonight")
require("colorschemes.everforest")
require("colorschemes.rose-pine")
require("colorschemes.iceberg")

vim.cmd("colorscheme rose-pine-moon")
-- vim.cmd("colorscheme rose-pine")
-- vim.cmd("colorscheme rose-pine-main")
-- vim.cmd("colorscheme rose-pine-dawn")
-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme catppuccin-nvim")
-- vim.cmd("colorscheme tokyonight-storm")
-- vim.cmd("colorscheme everforest")
-- vim.cmd("colorscheme iceberg")
